//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbGraf2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MercuryData
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateTimeStart { get; set; }
        public Nullable<double> Hg { get; set; }
        public string unit { get; set; }
    }
}
