//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbGraf2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeteorologiData
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<double> WindDirection { get; set; }
        public Nullable<double> WindSpeed { get; set; }
        public Nullable<double> Temperature { get; set; }
        public Nullable<double> Humidity { get; set; }
        public Nullable<double> Radiation { get; set; }
        public Nullable<double> Pressure { get; set; }
    }
}
